# -*- coding: utf-8 -*-
"""Copy of Data Table Display

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fK8fn_d7TlP3utCScCIb957YYghcYs1p
"""

!pip install prophet plotly scikit-learn

from google.colab import files
uploaded = files.upload()

m1_pulseguard_surya_fixed_2025_raw_heart_rate.csv

import pandas as pd
import numpy as np
from prophet import Prophet
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import plotly.express as px
import plotly.graph_objects as go
import warnings
warnings.filterwarnings("ignore")

# =========================================================
# LOAD DATA
# =========================================================
DATA_PATH = "m1_pulseguard_surya_fixed_2025_raw_heart_rate.csv"

df = pd.read_csv(DATA_PATH)

# Debugging: Print columns to verify
print("Columns in the DataFrame:", df.columns)

# Basic validation
required_cols = {"timestamp", "hr_bpm"}
assert required_cols.issubset(df.columns), "Dataset missing required columns"

df["timestamp"] = pd.to_datetime(df["timestamp"])
df = df.sort_values("timestamp")
df["heart_rate"] = df["hr_bpm"].clip(30, 220) # Corrected column name to 'hr_bpm'
df["heart_rate"].fillna(df["heart_rate"].mean(), inplace=True) # Fill NaN values in heart_rate

print("✅ Data Loaded:", df.shape)

# =========================================================
# FEATURE ENGINEERING
# =========================================================
df["hour"] = df["timestamp"].dt.hour
df["hr_diff"] = df["heart_rate"].diff().fillna(0)
df["rolling_hr"] = df["heart_rate"].rolling(5).mean().fillna(df["heart_rate"])

# =========================================================
# DATA PREVIEW
# =========================================================
df.head(10)

from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

fig = px.histogram(
    df,
    x="heart_rate",
    nbins=50,
    title="Heart Rate Distribution"
)
fig.show()

features = df[["heart_rate", "hr_diff", "rolling_hr"]]
scaled = StandardScaler().fit_transform(features)

kmeans = KMeans(n_clusters=3, random_state=42)
df["cluster"] = kmeans.fit_predict(scaled)

df["behavior"] = df["cluster"].map({
    0: "Resting",
    1: "Active",
    2: "Stressed"
})

fig_cluster = px.scatter(
    df,
    x="heart_rate",
    y="hr_diff",
    color="behavior",
    title="Behavior Clustering"
)
fig_cluster.show()

prophet_df = df.rename(columns={"timestamp": "ds", "heart_rate": "y"})

model = Prophet(daily_seasonality=True, weekly_seasonality=True)
model.fit(prophet_df)

forecast = model.predict(prophet_df)

df["yhat"] = forecast["yhat"]
df["yhat_upper"] = forecast["yhat_upper"]
df["yhat_lower"] = forecast["yhat_lower"]

fig_prophet = go.Figure()
fig_prophet.add_trace(go.Scatter(
    x=df["timestamp"], y=df["heart_rate"],
    mode="lines", name="Actual HR"
))
fig_prophet.add_trace(go.Scatter(
    x=df["timestamp"], y=df["yhat"],
    mode="lines", name="Forecast"
))
fig_prophet.show()

MAX_HR_THRESHOLD = 130

df["rule_anomaly"] = df["heart_rate"] > MAX_HR_THRESHOLD

df["residual"] = df["heart_rate"] - df["yhat"]
std = df["residual"].std()

df["residual_anomaly"] = abs(df["residual"]) > 3 * std

df["final_anomaly"] = df["rule_anomaly"] | df["residual_anomaly"]

print("🔴 Total Anomalies:", df["final_anomaly"].sum())

fig_anom = go.Figure()

fig_anom.add_trace(go.Scatter(
    x=df["timestamp"],
    y=df["heart_rate"],
    mode="lines",
    name="Heart Rate"
))

anomalies = df[df["final_anomaly"]]
fig_anom.add_trace(go.Scatter(
    x=anomalies["timestamp"],
    y=anomalies["heart_rate"],
    mode="markers",
    marker=dict(color="red", size=7),
    name="Anomaly"
))

fig_anom.show()

anomalies.head(20)

pip install streamlit pandas matplotlib plotly

plt.figure(figsize=(12,5))
plt.plot(final_df['timestamp'], final_df['heart_rate'])
plt.title("Heart Rate Over Time")
plt.xlabel("Time")
plt.ylabel("Heart Rate")
plt.show()

globals().keys()

BASE_PATH = "/content"

BASE_PATH = "/content/data"

import os
os.listdir("/content")

from google.colab import files
uploaded = files.upload()

import os
os.listdir("/content")

import pandas as pd

df = pd.read_csv("/content/m1_pulseguard_surya_fixed_2025_raw_heart_rate.csv")
df.head()

final_df.columns

CSV_PATH = "/content/m1_pulseguard_surya_fixed_2025_raw_heart_rate.csv"

final_df, features, prophet_df = fitpulse_milestone3_pipeline(CSV_PATH)

final_df.head()
final_df.columns

from IPython.display import Markdown, display
display(Markdown("## 🩺 FitPulse / PulseGuard – Health Anomaly Detection Dashboard"))

import matplotlib.pyplot as plt

plt.figure(figsize=(14,5))
plt.plot(final_df['timestamp'], final_df['heart_rate'], label='Heart Rate')
plt.title("Heart Rate Over Time")
plt.xlabel("Time")
plt.ylabel("Heart Rate (BPM)")
plt.legend()
plt.show()

anoms = final_df[final_df['anomaly'] == 1]

plt.figure(figsize=(14,5))
plt.plot(final_df['timestamp'], final_df['heart_rate'], label='Heart Rate')
plt.scatter(anoms['timestamp'], anoms['heart_rate'],
            color='red', label='Anomaly', s=30)

plt.title("Detected Heart Rate Anomalies")
plt.xlabel("Time")
plt.ylabel("Heart Rate (BPM)")
plt.legend()
plt.show()

total_records = len(final_df)
total_anomalies = final_df['anomaly'].sum()
normal_records = total_records - total_anomalies

print("📊 DASHBOARD SUMMARY")
print("Total Records        :", total_records)
print("Normal Records       :", normal_records)
print("Anomalies Detected   :", total_anomalies)

plt.figure(figsize=(14,5))
plt.plot(final_df['timestamp'], final_df['heart_rate'], label='Actual HR')
plt.plot(final_df['timestamp'], final_df['yhat'], label='Predicted HR')

plt.fill_between(
    final_df['timestamp'],
    final_df['yhat_lower'],
    final_df['yhat_upper'],
    alpha=0.3,
    label='Confidence Interval'
)

plt.title("Actual vs Predicted Heart Rate (Prophet)")
plt.xlabel("Time")
plt.ylabel("Heart Rate (BPM)")
plt.legend()
plt.show()

import plotly.express as px

fig = px.line(
    final_df,
    x='timestamp',
    y='heart_rate',
    title="Interactive Heart Rate Dashboard",
    labels={'heart_rate': 'Heart Rate (BPM)', 'timestamp': 'Time'}
)

# Add anomaly points
anoms = final_df[final_df['anomaly'] == 1]

fig.add_scatter(
    x=anoms['timestamp'],
    y=anoms['heart_rate'],
    mode='markers',
    marker=dict(color='red', size=6),
    name='Anomaly'
)

fig.show()

fig2 = px.line(
    final_df,
    x='timestamp',
    y=['heart_rate', 'yhat'],
    title="Actual vs Predicted Heart Rate (Prophet)",
    labels={'value': 'Heart Rate (BPM)', 'variable': 'Legend'}
)

fig2.show()

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# st.set_page_config(page_title="PulseGuard Dashboard", layout="wide")
# 
# st.title("🩺 PulseGuard – Health Anomaly Detection Dashboard")
# 
# # Load data
# df = pd.read_csv("m1_pulseguard_surya_fixed_2025_raw_heart_rate.csv")
# 
# # Summary
# st.subheader("📊 Summary")
# col1, col2 = st.columns(2)
# col1.metric("Total Records", len(df))
# col2.metric("Anomalies Detected", int(df['anomaly'].sum()))
# 
# # Interactive plot
# st.subheader("📈 Heart Rate with Anomalies")
# 
# fig = px.line(df, x='timestamp', y='heart_rate')
# 
# anoms = df[df['anomaly'] == 1]
# fig.add_scatter(
#     x=anoms['timestamp'],
#     y=anoms['heart_rate'],
#     mode='markers',
#     marker=dict(color='red', size=6),
#     name='Anomaly'
# )
# 
# st.plotly_chart(fig, use_container_width=True)
#

fig.show()

pip install streamlit

!python --version

!pip install streamlit pandas plotly prophet scikit-learn

final_df.to_csv("dashboard_data.csv", index=False)

from google.colab import files
files.download("dashboard_data.csv")

df = pd.read_csv("dashboard_data.csv")

!streamlit run app.py

import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="PulseGuard Dashboard", layout="wide")

st.title("🩺 PulseGuard – Health Anomaly Detection Dashboard")

df = pd.read_csv("m1_pulseguard_surya_fixed_2025_raw_heart_rate.csv")

col1, col2 = st.columns(2)
col1.metric("Total Records", len(df))
col2.metric("Anomalies Detected", int(df['anomaly'].sum()))

fig = px.line(df, x='timestamp', y='heart_rate')
anoms = df[df['anomaly'] == 1]

fig.add_scatter(
    x=anoms['timestamp'],
    y=anoms['heart_rate'],
    mode='markers',
    marker=dict(color='red', size=6),
    name='Anomaly'
)

st.plotly_chart(fig, use_container_width=True)

!streamlit run app.py